<a href="https://colab.research.google.com/github/isauraqinthara/FP-SoftComputing/blob/development/TPS_Surabaya_Pusat_Routing_Problem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# VRP SBY PUSAT WITH BENOWOOO

In [ ]:
import pandas as pd
import numpy as np
import random
from sklearn.cluster import KMeans
import folium
import math

In [ ]:
df = pd.read_csv('SURABAYA BENOWO TPS.csv')
df

,No,LPS/Depo,Alamat,Latitude,Longitude,Kapasitas_Sampah(m^3)
0,1,Demak (Kali Butuh),Jalan Demak,-7.253606,112.720422,13
1,2,Pringadi,Jalan Pringadi,-7.252544,112.733072,12
2,3,Penghela,Jalan Penghela,-7.248233,112.733186,16
3,4,Sulung Kali,Jalan Sulung Kali,-7.244014,112.742173,12
4,5,Dupak,Jalan Babatan Dupak,-7.244836,112.727439,13
5,6,Simolawang,Jalan Simolawang,-7.237522,112.753542,13
6,7,Pasar Kapasan,Jalan Simolawang Baru I,-7.239633,112.750247,14
7,8,Tambak Rejo,Jalan Kenjeran (depan Makam Rangkah),-7.243069,112.760314,16
8,9,Simpang Dukuh,Jalan Simpang Dukuh,-7.260503,112.742111,11
9,10,Pasar Genteng,Jalan Genteng Besar,-7.258242,112.740377,14
10,11,Kayun,Jalan Kayun,-7.269259,112.747528,15
11,12,Legundi Anggrek,Jalan Anggrek,-7.262483,112.752017,15
12,13,Pecindilan,Jalan Raya Pecindilan,-7.244094,112.747411,6
13,14,Makam Peneleh,Jalan Makam Peneleh,-7.252331,112.741364,6
14,15,Kedondong,Jalan Kedondong,-7.271773,112.738242,15
15,16,Kedung Anyar,Jalan Kedung Anyar,-7.254253,112.731048,15
16,17,Pasar Kembang,Jalan Wonorejo III Pasar,-7.269049,112.729097,15
17,18,Pandegiling,Jalan Pandegiling,-7.276231,112.735806,14
18,19,Dinoyo,Jalan Dinoyo,-7.278275,112.743403,15
19,20,Rumah Sakit Darmo / Ketampon,Jalan Taman Ketampon,-7.287677,112.736963,14
20,21,Keputran Selatan,Jalan Keputran Selatan,-7.274575,112.743370,14
21,22,3R Jambangan,Jalan Jambangan Kebon Agung,-7.313541,112.732069,8
22,23,Gayungsari,Jalan Gayungsari IV,-7.324832,112.749814,9
23,24,Nyamplungan,Jalan KH Mas Mansyur,-7.221696,112.750527,10
24,25,Kertopaten,Jalan Kertopaten,-7.230313,112.741019,6
25,26,Jagir,Jalan Bendul Merisi,-7.299018,112.753697,6
26,27,Prada Kali Kendal,Jalan Kali Kendal,-7.275311,112.695040,13
27,28,Wonokusumo Kidul,Jalan Wonokusumo Jaya,-7.225113,112.752340,14
28,29,Gubeng,Jalan Gubeng Kertajaya,-7.277812,112.761476,12
29,30,Sawahan,Jalan Sawahan Raya,-7.262594,112.728107,10
30,31,Kendung,Jalan Kendung,-7.247601,112.635484,11
31,32,Kenjeran,Jalan Kenjeran Utama,-7.244000,112.900000,18
32,33,Panghela,Jalan Panghela,-7.247908,112.733304,12
33,34,Giyu,Jalan Rungkut Industri,-7.331003,112.771393,13
34,35,Alas Malang,Jalan Alas Malang,-7.262228,112.643165,14
35,36,Babat Jerawat,Jalan DK Jerawat,-7.246167,112.629661,11
36,37,Srikana,Jalan Srikana,-7.273996,112.758097,8
37,38,Keputih,Jalan Raya Marina Asri,-7.294823,112.807148,8
38,39,Tambak Deres,Jalan Kyai Tambak Deres,-7.230860,112.785501,6
39,40,Pacar Keling,Jalan Tambang Boyo,-7.260621,112.758661,6
40,41,Kaiser,Jalan Makam,-7.276720,112.713377,17
41,42,Medokan Ayu,Jalan Medokan Asri Tengah,-7.326099,112.795516,17
42,43,Semolowaru Bahari,Jalan Semolowaru,-7.302239,112.788335,11
43,44,Gebang Putih,Jalan Gebang Putih,-7.284392,112.785407,11
44,45,Pesapen,Jalan Karang Ploso,-7.326542,112.674600,11

In [ ]:
df['lat'] = df['Latitude'].astype(str).str.replace('–','-').astype(float)
df['lon'] = df['Longitude'].astype(str).str.replace('–','-').astype(float)
df

,No,LPS/Depo,Alamat,Latitude,Longitude,Kapasitas_Sampah(m^3),lat,lon
0,1,Demak (Kali Butuh),Jalan Demak,-7.253606,112.720422,13,-7.253606,112.720422
1,2,Pringadi,Jalan Pringadi,-7.252544,112.733072,12,-7.252544,112.733072
2,3,Penghela,Jalan Penghela,-7.248233,112.733186,16,-7.248233,112.733186
3,4,Sulung Kali,Jalan Sulung Kali,-7.244014,112.742173,12,-7.244014,112.742173
4,5,Dupak,Jalan Babatan Dupak,-7.244836,112.727439,13,-7.244836,112.727439
5,6,Simolawang,Jalan Simolawang,-7.237522,112.753542,13,-7.237522,112.753542
6,7,Pasar Kapasan,Jalan Simolawang Baru I,-7.239633,112.750247,14,-7.239633,112.750247
7,8,Tambak Rejo,Jalan Kenjeran (depan Makam Rangkah),-7.243069,112.760314,16,-7.243069,112.760314
8,9,Simpang Dukuh,Jalan Simpang Dukuh,-7.260503,112.742111,11,-7.260503,112.742111
9,10,Pasar Genteng,Jalan Genteng Besar,-7.258242,112.740377,14,-7.258242,112.740377
10,11,Kayun,Jalan Kayun,-7.269259,112.747528,15,-7.269259,112.747528
11,12,Legundi Anggrek,Jalan Anggrek,-7.262483,112.752017,15,-7.262483,112.752017
12,13,Pecindilan,Jalan Raya Pecindilan,-7.244094,112.747411,6,-7.244094,112.747411
13,14,Makam Peneleh,Jalan Makam Peneleh,-7.252331,112.741364,6,-7.252331,112.741364
14,15,Kedondong,Jalan Kedondong,-7.271773,112.738242,15,-7.271773,112.738242
15,16,Kedung Anyar,Jalan Kedung Anyar,-7.254253,112.731048,15,-7.254253,112.731048
16,17,Pasar Kembang,Jalan Wonorejo III Pasar,-7.269049,112.729097,15,-7.269049,112.729097
17,18,Pandegiling,Jalan Pandegiling,-7.276231,112.735806,14,-7.276231,112.735806
18,19,Dinoyo,Jalan Dinoyo,-7.278275,112.743403,15,-7.278275,112.743403
19,20,Rumah Sakit Darmo / Ketampon,Jalan Taman Ketampon,-7.287677,112.736963,14,-7.287677,112.736963
20,21,Keputran Selatan,Jalan Keputran Selatan,-7.274575,112.743370,14,-7.274575,112.743370
21,22,3R Jambangan,Jalan Jambangan Kebon Agung,-7.313541,112.732069,8,-7.313541,112.732069
22,23,Gayungsari,Jalan Gayungsari IV,-7.324832,112.749814,9,-7.324832,112.749814
23,24,Nyamplungan,Jalan KH Mas Mansyur,-7.221696,112.750527,10,-7.221696,112.750527
24,25,Kertopaten,Jalan Kertopaten,-7.230313,112.741019,6,-7.230313,112.741019
25,26,Jagir,Jalan Bendul Merisi,-7.299018,112.753697,6,-7.299018,112.753697
26,27,Prada Kali Kendal,Jalan Kali Kendal,-7.275311,112.695040,13,-7.275311,112.695040
27,28,Wonokusumo Kidul,Jalan Wonokusumo Jaya,-7.225113,112.752340,14,-7.225113,112.752340
28,29,Gubeng,Jalan Gubeng Kertajaya,-7.277812,112.761476,12,-7.277812,112.761476
29,30,Sawahan,Jalan Sawahan Raya,-7.262594,112.728107,10,-7.262594,112.728107
30,31,Kendung,Jalan Kendung,-7.247601,112.635484,11,-7.247601,112.635484
31,32,Kenjeran,Jalan Kenjeran Utama,-7.244000,112.900000,18,-7.244000,112.900000
32,33,Panghela,Jalan Panghela,-7.247908,112.733304,12,-7.247908,112.733304
33,34,Giyu,Jalan Rungkut Industri,-7.331003,112.771393,13,-7.331003,112.771393
34,35,Alas Malang,Jalan Alas Malang,-7.262228,112.643165,14,-7.262228,112.643165
35,36,Babat Jerawat,Jalan DK Jerawat,-7.246167,112.629661,11,-7.246167,112.629661
36,37,Srikana,Jalan Srikana,-7.273996,112.758097,8,-7.273996,112.758097
37,38,Keputih,Jalan Raya Marina Asri,-7.294823,112.807148,8,-7.294823,112.807148
38,39,Tambak Deres,Jalan Kyai Tambak Deres,-7.230860,112.785501,6,-7.230860,112.785501
39,40,Pacar Keling,Jalan Tambang Boyo,-7.260621,112.758661,6,-7.260621,112.758661
40,41,Kaiser,Jalan Makam,-7.276720,112.713377,17,-7.276720,112.713377
41,42,Medokan Ayu,Jalan Medokan Asri Tengah,-7.326099,112.795516,17,-7.326099,112.795516
42,43,Semolowaru Bahari,Jalan Semolowaru,-7.302239,112.788335,11,-7.302239,112.788335
43,44,Gebang Putih,Jalan Gebang Putih,-7.284392,112.785407,11,-7.284392,112.785407
44,45,Pesapen,Jalan Karang Ploso,-7.326542,112.674600,11,-7.326542,112.674600

In [ ]:
# 3. Define depot (Pool) and TPA coordinates
pool = (-7.26053139, 112.692194)   # Pool Tanjungsari
tpa  = (-7.23739100, 112.60943600) # TPA Benowo

In [ ]:
df['lat'] = df['Latitude'].astype(str).str.replace('–','-').astype(float)
df['lon'] = df['Longitude'].astype(str).str.replace('–','-').astype(float)
df

,No,LPS/Depo,Alamat,Latitude,Longitude,Kapasitas_Sampah(m^3),lat,lon
0,1,Demak (Kali Butuh),Jalan Demak,-7.253606,112.720422,13,-7.253606,112.720422
1,2,Pringadi,Jalan Pringadi,-7.252544,112.733072,12,-7.252544,112.733072
2,3,Penghela,Jalan Penghela,-7.248233,112.733186,16,-7.248233,112.733186
3,4,Sulung Kali,Jalan Sulung Kali,-7.244014,112.742173,12,-7.244014,112.742173
4,5,Dupak,Jalan Babatan Dupak,-7.244836,112.727439,13,-7.244836,112.727439
5,6,Simolawang,Jalan Simolawang,-7.237522,112.753542,13,-7.237522,112.753542
6,7,Pasar Kapasan,Jalan Simolawang Baru I,-7.239633,112.750247,14,-7.239633,112.750247
7,8,Tambak Rejo,Jalan Kenjeran (depan Makam Rangkah),-7.243069,112.760314,16,-7.243069,112.760314
8,9,Simpang Dukuh,Jalan Simpang Dukuh,-7.260503,112.742111,11,-7.260503,112.742111
9,10,Pasar Genteng,Jalan Genteng Besar,-7.258242,112.740377,14,-7.258242,112.740377
10,11,Kayun,Jalan Kayun,-7.269259,112.747528,15,-7.269259,112.747528
11,12,Legundi Anggrek,Jalan Anggrek,-7.262483,112.752017,15,-7.262483,112.752017
12,13,Pecindilan,Jalan Raya Pecindilan,-7.244094,112.747411,6,-7.244094,112.747411
13,14,Makam Peneleh,Jalan Makam Peneleh,-7.252331,112.741364,6,-7.252331,112.741364
14,15,Kedondong,Jalan Kedondong,-7.271773,112.738242,15,-7.271773,112.738242
15,16,Kedung Anyar,Jalan Kedung Anyar,-7.254253,112.731048,15,-7.254253,112.731048
16,17,Pasar Kembang,Jalan Wonorejo III Pasar,-7.269049,112.729097,15,-7.269049,112.729097
17,18,Pandegiling,Jalan Pandegiling,-7.276231,112.735806,14,-7.276231,112.735806
18,19,Dinoyo,Jalan Dinoyo,-7.278275,112.743403,15,-7.278275,112.743403
19,20,Rumah Sakit Darmo / Ketampon,Jalan Taman Ketampon,-7.287677,112.736963,14,-7.287677,112.736963
20,21,Keputran Selatan,Jalan Keputran Selatan,-7.274575,112.743370,14,-7.274575,112.743370
21,22,3R Jambangan,Jalan Jambangan Kebon Agung,-7.313541,112.732069,8,-7.313541,112.732069
22,23,Gayungsari,Jalan Gayungsari IV,-7.324832,112.749814,9,-7.324832,112.749814
23,24,Nyamplungan,Jalan KH Mas Mansyur,-7.221696,112.750527,10,-7.221696,112.750527
24,25,Kertopaten,Jalan Kertopaten,-7.230313,112.741019,6,-7.230313,112.741019
25,26,Jagir,Jalan Bendul Merisi,-7.299018,112.753697,6,-7.299018,112.753697
26,27,Prada Kali Kendal,Jalan Kali Kendal,-7.275311,112.695040,13,-7.275311,112.695040
27,28,Wonokusumo Kidul,Jalan Wonokusumo Jaya,-7.225113,112.752340,14,-7.225113,112.752340
28,29,Gubeng,Jalan Gubeng Kertajaya,-7.277812,112.761476,12,-7.277812,112.761476
29,30,Sawahan,Jalan Sawahan Raya,-7.262594,112.728107,10,-7.262594,112.728107
30,31,Kendung,Jalan Kendung,-7.247601,112.635484,11,-7.247601,112.635484
31,32,Kenjeran,Jalan Kenjeran Utama,-7.244000,112.900000,18,-7.244000,112.900000
32,33,Panghela,Jalan Panghela,-7.247908,112.733304,12,-7.247908,112.733304
33,34,Giyu,Jalan Rungkut Industri,-7.331003,112.771393,13,-7.331003,112.771393
34,35,Alas Malang,Jalan Alas Malang,-7.262228,112.643165,14,-7.262228,112.643165
35,36,Babat Jerawat,Jalan DK Jerawat,-7.246167,112.629661,11,-7.246167,112.629661
36,37,Srikana,Jalan Srikana,-7.273996,112.758097,8,-7.273996,112.758097
37,38,Keputih,Jalan Raya Marina Asri,-7.294823,112.807148,8,-7.294823,112.807148
38,39,Tambak Deres,Jalan Kyai Tambak Deres,-7.230860,112.785501,6,-7.230860,112.785501
39,40,Pacar Keling,Jalan Tambang Boyo,-7.260621,112.758661,6,-7.260621,112.758661
40,41,Kaiser,Jalan Makam,-7.276720,112.713377,17,-7.276720,112.713377
41,42,Medokan Ayu,Jalan Medokan Asri Tengah,-7.326099,112.795516,17,-7.326099,112.795516
42,43,Semolowaru Bahari,Jalan Semolowaru,-7.302239,112.788335,11,-7.302239,112.788335
43,44,Gebang Putih,Jalan Gebang Putih,-7.284392,112.785407,11,-7.284392,112.785407
44,45,Pesapen,Jalan Karang Ploso,-7.326542,112.674600,11,-7.326542,112.674600

In [ ]:
# 5. Cluster into number of arm-roll trucks (HCS)
n_vehicles = 11
coords = df[['lat','lon']].values
kmeans = KMeans(n_clusters=n_vehicles, random_state=42).fit(coords)
df['cluster'] = kmeans.labels_

In [ ]:
#Clustering Folium Visualization

# Define a color map for clusters
colors = ['blue', 'purple', 'orange', 'darkred', 'lightred', 'darkblue', 'darkgreen', 'cadetblue', 'darkpurple', 'pink', 'lightblue']

# Create a new map centered at the pool
m_cluster = folium.Map(location=pool, zoom_start=12)

# Add depot and TPA markers
folium.Marker(location=pool, popup='Pool Tanjungsari', icon=folium.Icon(color='red')).add_to(m_cluster)
folium.Marker(location=tpa, popup='TPA Benowo', icon=folium.Icon(color='green')).add_to(m_cluster)

# Add markers for each point, colored by cluster
for _, row in df.iterrows():
    folium.Marker(location=(row['lat'], row['lon']),
                  popup=f"{row['LPS/Depo']} (Cluster {row['cluster']})",
                  icon=folium.Icon(color=colors[row['cluster'] % len(colors)])).add_to(m_cluster)

# Display the map
m_cluster

In [ ]:
# 6. Utility functions for GA-based TSP
def haversine(a, b):
    R = 6371e3
    φ1, φ2 = math.radians(a[0]), math.radians(b[0])
    Δφ = math.radians(b[0] - a[0])
    Δλ = math.radians(b[1] - a[1])
    x = math.sin(Δφ/2)**2 + math.cos(φ1)*math.cos(φ2)*math.sin(Δλ/2)**2
    return R * 2 * math.asin(math.sqrt(x))

In [ ]:
def route_distance(route):
    dist = 0
    prev = pool
    for pt in route:
        dist += haversine(prev, pt)
        prev = pt
    dist += haversine(prev, tpa) + haversine(tpa, pool)
    return dist

In [ ]:
def order_crossover(p1, p2):
    size = len(p1)
    a, b = sorted(random.sample(range(size), 2))
    c1 = [None]*size
    c2 = [None]*size
    c1[a:b], c2[a:b] = p1[a:b], p2[a:b]
    def fill(child, parent):
        pos = b
        for gene in parent[b:] + parent[:b]:
            if gene not in child:
                if pos >= size: pos = 0
                child[pos] = gene
                pos += 1
    fill(c1, p2)
    fill(c2, p1)
    return c1, c2

In [ ]:
def mutate(ind):
    if len(ind) > 1:
        i, j = random.sample(range(len(ind)), 2)
        ind[i], ind[j] = ind[j], ind[i]

In [ ]:
def ga_cluster(points, pop_size=200, gens=1000, elite_size=1):
    n = len(points)
    if n < 2:
        return points

    # initialize population
    population = [random.sample(range(n), n) for _ in range(pop_size)]

    for _ in range(gens):
        # compute fitness for roulette selection
        fitness = [1/(route_distance([points[i] for i in ind]) + 1) for ind in population]
        total = sum(fitness)
        probs = [f/total for f in fitness]

        # select elites (best individuals) to carry forward
        sorted_pop = sorted(
            population,
            key=lambda ind: route_distance([points[i] for i in ind])
        )
        new_pop = [sorted_pop[i].copy() for i in range(elite_size)]

        # fill the rest of new_pop by crossover + mutation
        while len(new_pop) < pop_size:
            # select two parents
            p1, p2 = random.choices(population, probs, k=2)
            # crossover
            if random.random() < 0.8:
                c1, c2 = order_crossover(p1, p2)
            else:
                c1, c2 = p1[:], p2[:]
            # mutate
            if random.random() < 0.2:
                mutate(c1)
            if random.random() < 0.2:
                mutate(c2)

            new_pop.append(c1)
            if len(new_pop) < pop_size:
                new_pop.append(c2)

        population = new_pop

    # return the best route as actual coordinates
    best = min(
        population,
        key=lambda ind: route_distance([points[i] for i in ind])
    )
    return [points[i] for i in best]

In [ ]:
# 7. Compute and display GA-based VRP routes
m2 = folium.Map(location=pool, zoom_start=12)
folium.Marker(location=pool, popup='Pool Tanjungsari', icon=folium.Icon(color='red')).add_to(m2)
folium.Marker(location=tpa, popup='TPA Benowo', icon=folium.Icon(color='green')).add_to(m2)

In [ ]:
colors = [
    'blue','green','purple','orange','darkred',
    'cadetblue','darkgreen','pink','lightgray',
    'beige','darkblue'
]
coord_to_name = {
    (row['lat'], row['lon']): row['LPS/Depo']
    for _, row in df.iterrows()
}
coord_to_name[pool] = "Pool Tanjungsari"
coord_to_name[tpa]  = "TPA Benowo"

for vid in range(n_vehicles):
    # get the raw coordinates in this cluster
    cluster_pts = coords[kmeans.labels_ == vid]
    if len(cluster_pts) == 0:
        continue

    # GA wants a Python list of tuple‐points
    pts_list = [tuple(pt) for pt in cluster_pts]

    # find best ordering of stops
    best_route = ga_cluster(pts_list)

    # build the full trip for plotting
    full_route = [pool] + best_route + [tpa, pool]

    # 1) draw it on the map
    folium.PolyLine(
        locations=full_route,
        color=colors[vid % len(colors)],
        weight=2.5, opacity=0.8,
        popup=f'Vehicle {vid+1}'
    ).add_to(m2)

    # 2) compute the true total distance via route_distance(best_route)
    #    (it already adds pool→stops→TPA→pool)
    total_dist_km = route_distance(best_route) / 1000

    # 3) map coords back to names
    path_names = [coord_to_name[c] for c in full_route]
    print(f"Vehicle {vid+1}: " + " → ".join(path_names))
    print(f"  Total distance: {total_dist_km:.2f} km\n")

# finally show the map
m2

Vehicle 1: Pool Tanjungsari → Pasar Kembang → Pandegiling → Kedondong → Keputran Selatan → Dinoyo → Rumah Sakit Darmo / Ketampon → TPA Benowo → Pool Tanjungsari
  Total distance: 32.77 km

Vehicle 2: Pool Tanjungsari → Gebang Putih → Keputih → Semolowaru Bahari → TPA Benowo → Pool Tanjungsari
  Total distance: 46.01 km

Vehicle 3: Pool Tanjungsari → Pecindilan → Pasar Kapasan → Simolawang → Tambak Rejo → Tambak Deres → Wonokusumo Kidul → Nyamplungan → Kertopaten → TPA Benowo → Pool Tanjungsari
  Total distance: 41.02 km

Vehicle 4: Pool Tanjungsari → Alas Malang → Kendung → Babat Jerawat → TPA Benowo → Pool Tanjungsari
  Total distance: 19.83 km

Vehicle 5: Pool Tanjungsari → Jagir → Giyu → Gayungsari → 3R Jambangan → TPA Benowo → Pool Tanjungsari
  Total distance: 42.32 km

Vehicle 6: Pool Tanjungsari → Kenjeran → TPA Benowo → Pool Tanjungsari
  Total distance: 64.54 km

Vehicle 7: Pool Tanjungsari → Kayun → Srikana → Gubeng → Pacar Keling → Legundi Anggrek → TPA Benowo → Pool Tanjungsari
  Total distance: 36.18 km

Vehicle 8: Pool Tanjungsari → Pesapen → TPA Benowo → Pool Tanjungsari
  Total distance: 29.32 km

Vehicle 9: Pool Tanjungsari → Demak (Kali Butuh) → Dupak → Sulung Kali → Makam Peneleh → Simpang Dukuh → Pasar Genteng → Panghela → Penghela → Pringadi → Kedung Anyar → Sawahan → TPA Benowo → Pool Tanjungsari
  Total distance: 34.29 km

Vehicle 10: Pool Tanjungsari → Medokan Ayu → TPA Benowo → Pool Tanjungsari
  Total distance: 45.78 km

Vehicle 11: Pool Tanjungsari → Kaiser → Prada Kali Kendal → TPA Benowo → Pool Tanjungsari
  Total distance: 24.80 km

In [30]:
#SA Function
def simulated_annealing(points, volumes, capacity, initial_temp=500, cooling_rate=0.98, stop_temp=10):
    from functools import lru_cache

    n = len(points)
    current = list(range(n))
    random.shuffle(current)

    def total_distance(route):
        dist = 0
        prev = pool
        for idx in route:
            dist += haversine(prev, points[idx])
            prev = points[idx]
        dist += haversine(prev, tpa) + haversine(tpa, pool)
        return dist

    def is_valid(route):
        load = 0
        for i in route:
            load += volumes[i]
            if load > capacity:
                return False
        return True

    # Cari solusi awal yang valid
    tries = 0
    while not is_valid(current):
        random.shuffle(current)
        tries += 1
        if tries > 1000:
            raise Exception("Gagal mendapatkan solusi awal yang valid")

    best = current[:]
    best_dist = total_distance(best)
    temp = initial_temp
    iter_count = 0

    while temp > stop_temp:
        iter_count += 1
        neighbor = current[:]
        i, j = random.sample(range(n), 2)
        neighbor[i], neighbor[j] = neighbor[j], neighbor[i]

        if not is_valid(neighbor):
            temp *= cooling_rate
            continue

        curr_dist = total_distance(current)
        neighbor_dist = total_distance(neighbor)
        delta = neighbor_dist - curr_dist

        if delta < 0 or math.exp(-delta / temp) > random.random():
            current = neighbor
            if neighbor_dist < best_dist:
                best = neighbor[:]
                best_dist = neighbor_dist

        temp *= cooling_rate

        if iter_count % 100 == 0:
            print(f"  Iterasi {iter_count}, suhu: {temp:.2f}, best: {best_dist/1000:.2f} km")

    return [points[i] for i in best]

In [31]:
# Visualisasi Rute SA

# Parameter kapasitas truk
vehicle_capacity = 100.0

# Inisialisasi peta
m_sa = folium.Map(location=pool, zoom_start=12)
folium.Marker(location=pool, popup='Pool Tanjungsari', icon=folium.Icon(color='red')).add_to(m_sa)
folium.Marker(location=tpa, popup='TPA Benowo', icon=folium.Icon(color='green')).add_to(m_sa)

# Loop setiap kendaraan/cluster
for vid in range(n_vehicles):
    print(f"⏳ Processing Vehicle {vid+1}...")

    # Ambil titik & volume untuk cluster ini
    cluster_pts = coords[kmeans.labels_ == vid]
    cluster_volumes = df[df['cluster'] == vid]['Kapasitas_Sampah(m^3)'].values

    if len(cluster_pts) == 0:
        print(f"⚠️ Vehicle {vid+1} has no assigned points.\n")
        continue

    total_volume = cluster_volumes.sum()
    if total_volume > vehicle_capacity:
        print(f"⚠️ Vehicle {vid+1}: Total volume {total_volume:.2f} m³ exceeds capacity ({vehicle_capacity} m³), skipping...\n")
        continue

    # Format koordinat
    pts_list = [tuple(pt) for pt in cluster_pts]

    # Jika hanya 1 titik, langsung gunakan tanpa optimasi
    if len(pts_list) < 2:
        print(f"⚠️ Vehicle {vid+1} hanya memiliki 1 titik, langsung digunakan tanpa optimasi.\n")
        best_route = pts_list
    else:
        # Jalankan SA
        best_route = simulated_annealing(
            pts_list, cluster_volumes,
            capacity=vehicle_capacity,
            initial_temp=200,
            cooling_rate=0.95,
            stop_temp=10
        )

    # Bangun rute lengkap
    full_route = [pool] + best_route + [tpa, pool]

    # Tambahkan ke peta
    folium.PolyLine(
        locations=full_route,
        color=colors[vid % len(colors)],
        weight=2.5, opacity=0.8,
        popup=f'SA Vehicle {vid+1}'
    ).add_to(m_sa)

    # Cetak hasil rute
    path_names = [coord_to_name[c] for c in full_route]
    total_dist_km = route_distance(best_route) / 1000
    print(f"[SA] Vehicle {vid+1}: " + " → ".join(path_names))
    print(f"     Total distance: {total_dist_km:.2f} km\n")

# Tampilkan peta hasil SA
m_sa

⏳ Processing Vehicle 1...
[SA] Vehicle 1: Pool Tanjungsari → Rumah Sakit Darmo / Ketampon → Dinoyo → Keputran Selatan → Kedondong → Pandegiling → Pasar Kembang → TPA Benowo → Pool Tanjungsari
     Total distance: 32.91 km

⏳ Processing Vehicle 2...
[SA] Vehicle 2: Pool Tanjungsari → Gebang Putih → Keputih → Semolowaru Bahari → TPA Benowo → Pool Tanjungsari
     Total distance: 46.01 km

⏳ Processing Vehicle 3...
[SA] Vehicle 3: Pool Tanjungsari → Pasar Kapasan → Simolawang → Tambak Rejo → Tambak Deres → Wonokusumo Kidul → Nyamplungan → Kertopaten → Pecindilan → TPA Benowo → Pool Tanjungsari
     Total distance: 43.28 km

⏳ Processing Vehicle 4...
[SA] Vehicle 4: Pool Tanjungsari → Alas Malang → Kendung → Babat Jerawat → TPA Benowo → Pool Tanjungsari
     Total distance: 19.83 km

⏳ Processing Vehicle 5...
[SA] Vehicle 5: Pool Tanjungsari → 3R Jambangan → Gayungsari → Giyu → Jagir → TPA Benowo → Pool Tanjungsari
     Total distance: 43.02 km

⏳ Processing Vehicle 6...
⚠️ Vehicle 6 hanya memiliki 1 titik, langsung digunakan tanpa optimasi.

[SA] Vehicle 6: Pool Tanjungsari → Kenjeran → TPA Benowo → Pool Tanjungsari
     Total distance: 64.54 km

⏳ Processing Vehicle 7...
[SA] Vehicle 7: Pool Tanjungsari → Kayun → Legundi Anggrek → Pacar Keling → Gubeng → Srikana → TPA Benowo → Pool Tanjungsari
     Total distance: 36.72 km

⏳ Processing Vehicle 8...
⚠️ Vehicle 8 hanya memiliki 1 titik, langsung digunakan tanpa optimasi.

[SA] Vehicle 8: Pool Tanjungsari → Pesapen → TPA Benowo → Pool Tanjungsari
     Total distance: 29.32 km

⏳ Processing Vehicle 9...
⚠️ Vehicle 9: Total volume 134.00 m³ exceeds capacity (100.0 m³), skipping...

⏳ Processing Vehicle 10...
⚠️ Vehicle 10 hanya memiliki 1 titik, langsung digunakan tanpa optimasi.

[SA] Vehicle 10: Pool Tanjungsari → Medokan Ayu → TPA Benowo → Pool Tanjungsari
     Total distance: 45.78 km

⏳ Processing Vehicle 11...
[SA] Vehicle 11: Pool Tanjungsari → Kaiser → Prada Kali Kendal → TPA Benowo → Pool Tanjungsari
     Total distance: 24.80 km